### PR TITLE
fixed root targeting (v-calendar)

### PR DESCRIPTION
**Pull request by jsaucedo294**

### CODE REVIEW

**Review by jkmounts — DISMISSED** [review]
Nice. Was curious if there was a way to check for root with $refs. Hadn't come across the getRootNode().

**Comment by jsaucedo294** [comment]
@jkmounts - I'm not 100% sure if it will work though. We need to handle the possibility of having multiple shadow dom in our app. The utility app has multiple suites that will use also the date-picker. Here are some links about that method and the ShadowRoot.host
- `getRootNode()`: https://developer.mozilla.org/en-US/docs/Web/API/Node/getRootNode
- `ShadowRoot.host`: https://developer.mozilla.org/en-US/docs/Web/API/ShadowRoot/host

Do you mind double-checking that it works in the utility, admin, and home app?

**Comment by jkmounts** [comment]
@jsaucedo294 yes- I will take a look.

**Comment by jkmounts** [comment]
@jsaucedo294 - At first glance, it looks like `ShadowRoot.host` is taking us back outside the shadow-root. However, in my initial tests, the `getRootNode()` appears to be targeting the shadow-root if it exists or the document respectively. Still checking through all apps.

**Comment by jkmounts** [comment]
Modified to just return results of `getRootNode()` which defaults to the document if no shadow-root exists. Tested in home app, admin app, utility apps suite structure, and vcl.

**Review by jkmounts — APPROVED** [review]

**Pull request merged**
