### PR TITLE
Adding tabindex=0 to prev and next buttons so they can gain keyboard …

### PR DESCRIPTION
**Pull request by toddhudgens**
Fixes virtual-peaker/product-vp#986 Adding tabindex=0 so that the previous and next buttons can be focused with the keyboard.

### CODE REVIEW

**Review by jkmounts — APPROVED** [review]
Ran the VCL demo with this branch and everything appears to be working as expected. I was able to tab through the arrows inside the calendar popover and use them to change months which I believe is the intention.

**Comment by toddhudgens** [comment]
@josephmudd This is ready to be merged.

**Comment by josephmudd** [comment]
@toddhudgens - this has been deployed to dev. I don't see an issue attached here, but would you coordinate with Emily Keller to verify the fix in dev?

**Comment by toddhudgens** [comment]
> @toddhudgens - this has been deployed to dev. I don't see an issue attached here, but would you coordinate with Emily Keller to verify the fix in dev?

I just linked the issue, it's product-vp#986

There is an additional PR for the home app that will fix this issue for the event day widget. Once that is approved/merged/deployed we should be good to test.

https://github.com/virtual-peaker/home-webapp-angular/pull/400

**Pull request merged**
